stop-words = "stopwords.txt"
index = "idx"
corpus = "line.toml"
prefix = "/Users/Diana/OneDrive/Desktop/Github/CourseProject"
dataset = "course"
[[analyzers]]
	filter = "default-unigram-chain"
	method = "ngram-word"
	ngram = 1
