stop-words = "stopwords.txt"
index = "idx"
corpus = "line.toml"
dataset = "course"
prefix = "/Users/kartikpatel/Desktop/CS 410/Final Project/CourseProject"
[[analyzers]]
	filter = "default-unigram-chain"
	ngram = 1
	method = "ngram-word"
