prefix = "/Users/Diana/OneDrive/Desktop/Github/CourseProject"
dataset = "course"
corpus = "line.toml"
index = "idx"

stop-words = "stopwords.txt"

[[analyzers]]
method = "ngram-word"
ngram = 1
filter = "default-unigram-chain"

